---
title: "First Knit"
author: "Kimberly Salazar"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question. 
  
### my answer     
  Yes, I went to San Fernando High School and graduated with the class of 2019. Personally I find math easier for me although it is more challenging than English. The subject I have always done best in is math. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have an Apple laptop that I am very familiar with and have access to it daily. On the scale form 1 to 10 I rate myself a 8 only because I haven't came across a problem that I haven't been able to figure out. The internet connection I have is pretty fast almost every time and never has it given me a problem.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I prefer and respond more to my nickname which is Kim. But I do not mind being called by my full name.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  In life I want to achieve my career goals which is to become a child services social worker. Any sociology course will be my greatest interest to me because it related towards the work field I wish to reach. I am working towards completing my AA degree in order to transfer to a Cal State and work on a BS degree. My goal with this career is just to really help families during their hardships.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have never but in the future, hopefully in the next year I would like to visit Mexico. I want Mexico to be my first country because that is where most of my family is so before exploring other countries I would like to reunite with them. No, I have never been in the military but if I get drafted I would honestly like to go to the air force. My reason for this is becasue I am more familiar with that branch than with any other branch.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
  I am taking Math 116 for a requirement I need and because I'm not well in statistics and would like to learn and understand the concept. I knew this course is transferable which works great for me because my plan after AVC is to transfer to a Cal State. In my plans I need an B but will be aiming for an A for a better GPA. It will also help me and my pace in completing course rather than having to retake courses.
 






  




